dist: trusty
language: python
python:
  - 3.5

before_install:
    - sudo apt-get install -y libhidapi-dev libhidapi-libusb0
    - sudo apt-get install -y g++-mingw-w64-i686 gcc-mingw-w64-i686
    - sudo apt-get install -y python3-requests

cache:
    directories:
        - $HOME/.cache/flightpanel

script: python3 .travis.py
