dist: trusty
language: python
python:
    - 3.5

branches:
    only:
        - master

before_install:
    - sudo apt-get install -y libhidapi-dev libhidapi-libusb0
    - sudo apt-get install -y g++-mingw-w64-i686 gcc-mingw-w64-i686
    - pip3 install requests

cache:
    directories:
        - $HOME/.cache/flightpanel

script: python3 -m travis-deploy --build-everything --parallel 2

env:
    global:
        # Set CACHE_FILE_UPSTREAM_URI
        - secure: "D0HuNrYwRdjAYuYX8lUpE8SRXzs1NgSEcXOXfqUSYEucRFGcMsnr+yXGbRPrmJ78TtiWKVUeD9ZJeWxDlgJlzVKuQpWdc5L853DonZysLHMhnQ9Urc8HCY8rHB7GNRLi5cqs/71rYeBAEAseVpZcWApuvHO8pGLtpszyFR8QalXmiZddkQxcwLvw97BU1UCzpvhwXnlwt1auVz6HObclxmY2/WPRcBKrDlg7WUdKICOEvovAorMixikRbjlqnhWudYdozv18yKbXJ39nMrmBKrcvgyCtQgPYb6AXMRK5RGUGTYN42zEvspSHvOys2+sIY3iWmnW0+LSVVJdLfwwFNNTzhEQTj6I+pa4t1bmid/yMjtQyfBrnp1yiK+g//oEENJexkdfby053k7e+NTaTruk44bvcEXthOtI+jYKEh3cjBKox1zT4SB5lnVR/o5xUVGafnzI1Bz3b6h2lXDO4b6pFbn4eel2LQQz4pVYZZuDeCERss5Yenj3+zvKMhJ0/3RaK0V8ySlBJnHDw6rUVebGjws18JUPDl0sk3mTRIURMOU8kEs5N0fszdG3Vd3r4BmQsiSOAkOHCwtwnDqRoSLnGzFrm3D7yRregMz7fno/dYSnj0S08qylAiiRnevBGx/WsrzsVffL2qJwvbylQOZY2p8G6VFIa3wTY3mLjtxw="

        # Set GITHUB_ACCESS_TOKEN
        - secure: "yor9jFdyciwLWKzh3Nn7tfor5LGXKi5/ZcvaIYmDOiaE6aWgfY4eslGQcJKwL1zKs0FXk/HCIFHfEF6y3zgNFhwG4woHFdB0FEeYpq7M+wDmKQdc76E2gXKKxsRSmURVMCGh6LGxcCBNWi39Jscr1qf5FawtqLWWJixxYpq5u5179cfkc2uWKKrLzEftuAdy8DfiJ9cLy5OYp1Kz0do/g4y+I0rvEGWYNjG0olTqilKlV7qF9bLY8iGVUVjFHjxLPAlDTiPWmqyFhevLFKxRfzELZRCCjT7kOP1FjPWp+IHlMfFXbB0ct4u2Hym3H1dMo3dZH+OZpuHP15Vk+91T1Qtuy+8htA+T8hr3CphZaBJ9z1/5qeQ6EqUV1hZSLKm5YLvvVSfj7nKUTfm1ONil6QScqTC0uOkXNBgl7d+khY3HeIZgqdHBCmLtWjvWbqmNMIEQRA0LUUOSNVthRLK+zWdDq0XAyY9Fa+H7Iig2zBTKh7FbM1Jq+ASbwEflYq9wR1npTr3AZIERRwo+itmgjNC4TTgC+o1FDbzzr7gX3c0Q2k3z+o2UjEtebXjnRLKe558TwwFDFtz/ZgoXQn8KTpXMGK71jlNQs8Rt3jaoZRg42HZC01/yLArwLoKOb4BBP3Pjx2g//WG12X3ExI1goZxbOop1azwKwVSmKZ5PSU0="
