#!/usr/bin/python3
#
#	flightpanel - A Cortex-M4 based USB flight panel for flight simulators.
#	Copyright (C) 2017-2017 Johannes Bauer
#
#	This file is part of flightpanel.
#
#	flightpanel is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	flightpanel is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with flightpanel; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from XMLParser import XMLParser

input_svg = sys.argv[1]

xml = XMLParser().parsefile(input_svg)
for tag in xml.search("image"):
	tag["style"] = "opacity:1"
for tag in xml.search("path"):
	tag["style"] += ";opacity:0"
for tag in xml.search("circle"):
	tag["style"] += ";opacity:0"
for tag in xml.search("rect"):
	if not "pattern" in tag["style"]:
		tag["style"] += ";opacity:0"
with open("only_images.svg", "w") as f:
	xml.write(f)

xml = XMLParser().parsefile(input_svg)
for tag in xml.search("image"):
	tag["style"] = "opacity:0"
with open("no_images.svg", "w") as f:
	xml.write(f)
