#!/bin/bash
#
#

./font-rasterize --antialias gray --fontsize 20 "Helvetica" morse-font.json
./font-rasterize --antialias good --fontsize 20 "VCR OSD Mono" vcr-osd-mono-20.json
./font-rasterize --antialias good --fontsize 30 "VCR OSD Mono" vcr-osd-mono-30.json
./json-to-c.py --force --charset " •-" --patch '•:movey:1' --patch '•:rename:.' --create-pnm morse-font.json
./json-to-c.py --force vcr-osd-mono-20.json
./json-to-c.py --force --charset ". 0123456789 AP OFF" --threshold 0xd6 \
	--patch '.:setwidth:13' \
	vcr-osd-mono-30.json

cp vcr-osd-mono-20.c vcr-osd-mono-20.h ../firmware
cp vcr-osd-mono-30.c vcr-osd-mono-30.h ../firmware
cp morse-font.c morse-font.h ../firmware

#	--patch '0:setpixel:3:15' \
#	--patch '0:setpixel:3:16' \
